"""add contracts metadata

Revision ID: 86d1dfd3d6d0
Revises: 9ff51b90e284
Create Date: 2026-02-05 19:14:53.736849

"""
from alembic import op
import sqlalchemy as sa

revision = '86d1dfd3d6d0'
down_revision = '9ff51b90e284'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_backend', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column("processing_status", sa.String(length=30), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_contracts_sha256_hex', 'contracts', ['sha256_hex'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contracts_sha256_hex', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
