"""baseline

Revision ID: 9c2b51f39f22
Revises: 
Create Date: 2026-02-05 17:30:41.262979

"""
from alembic import op
import sqlalchemy as sa

revision = '9c2b51f39f22'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_clause_types_name')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clause_types')
    # ### end Alembic commands ###
