"""add clause patterns

Revision ID: 9ff51b90e284
Revises: 9c2b51f39f22
Create Date: 2026-02-05 18:00:32.882391

"""
from alembic import op
import sqlalchemy as sa

revision = '9ff51b90e284'
down_revision = '9c2b51f39f22'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_type_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['clause_type_id'], ['clause_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clause_patterns_clause_type_id', 'clause_patterns', ['clause_type_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clause_patterns_clause_type_id', table_name='clause_patterns')
    op.drop_table('clause_patterns')
    # ### end Alembic commands ###
