"""add contract clauses matrix

Revision ID: b6d971e24198
Revises: 622398860f71
Create Date: 2026-02-05 20:13:53.691583

"""
from alembic import op
import sqlalchemy as sa

revision = 'b6d971e24198'
down_revision = '622398860f71'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clause_type_id', sa.Integer(), nullable=False),
    sa.Column('detected', sa.Boolean(),server_default=sa.text('false'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_type_id'], ['clause_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'clause_type_id', name='uq_contract_clauses_contract_clause')
    )
    op.create_index('ix_contract_clauses_clause_type_id', 'contract_clauses', ['clause_type_id'], unique=False)
    op.create_index('ix_contract_clauses_contract_id', 'contract_clauses', ['contract_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contract_clauses_contract_id', table_name='contract_clauses')
    op.drop_index('ix_contract_clauses_clause_type_id', table_name='contract_clauses')
    op.drop_table('contract_clauses')
    # ### end Alembic commands ###
